project:
  type: website

website:
  title: "ISSS608new"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu: 
      - text: "Hands-on Exercise 1"
        href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
      - text: "Hands-on Exercise 2"
        href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
      - text: "Hands-on Exercise 3"
        href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
      - text: "Hands-on Exercise 4"
        href: "" 
      - text: "Hands-on Exercise 5"
        href: "" 
      - text: "Hands-on Exercise 6"
        href: "" 
      - text: "Hands-on Exercise 7"
        href: "" 
      - text: "Hands-on Exercise 8"
        href: "" 
      - text: "Hands-on Exercise 9"
        href: "" 
      - text: "Hands-on Exercise 10"
        href: "" 
        
    - text: "In-class Exercise"
      menu:
      - text: "In-class Exercise 1"
        href: ""
      - text: "In-class Exercise 2"
        href: ""
      - text: "In-class Exercise 3"
        href: ""
      - text: "In-class Exercise 4"
        href: ""
      - text: "In-class Exercise 5"
        href: ""
      - text: "In-class Exercise 6"
        href: ""
      - text: "In-class Exercise 7"
        href: ""
      - text: "In-class Exercise 8"
        href: ""
      - text: "In-class Exercise 9"
        href: ""
      - text: "In-class Exercise 10"
        href: ""
        
    - text: "Take-home Exercise"
      menu:
      - text: "Take-home Exercise 1"
        href: ""
      - text: "Take-home Exercise 2"
        href: ""
      - text: "Take-home Exercise 3"
        href: ""
  
        
    right: 
      - href: index.qmd
        text: Home
      - about.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

